sudo: required
services:
  - docker

before_install: 
  - docker build -t jjtai/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run -e CI=true jjtai/docker-react-tutorial npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react-tutorial"
  env: "Dockerreacttutorial-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-200250313593"
  bucket_path: "docker-react-tutorial"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

language: generic 